name: deployment
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  POSTGRES_DB: perfectc9
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    if: github.ref_name == 'production' # only test for production git branch
    runs-on: ubuntu-latest
    # container: node:latest
    # services:
    #   postgres:
    #     image: postgres:13
    #     env: 
    #       DB_NAME: ${{env.POSTGRES_DB}}
    #       DB_USER: ${{env.POSTGRES_USER}}
    #       DB_PASSWORD: ${{env.POSTGRES_PASSWORD}}
    #     ports:
    #       - 5432:5432
    steps:
      - name: Doing testing
        uses: fifsky/ssh-action@master
        with:
          command: |
            cat ~/.ssh/id_rsa
            cd perfect-c9/
            git pull
            yarn install 
            yarn jest --forceExit
          host: perfect-c9.homes
          user: ubuntu
          key: ${{secrets.DEPLOY}}

  deploy:
    if: github.ref_name == 'production' # only deploy for production git branch # pm2 start index.js --name "Express Server"
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - name: ssh to pull latest version
      uses: fifsky/ssh-action@master
      with:
        command: |
          cat ~/.ssh/id_rsa
          cd perfect-c9/
          git pull
          npm install
        host: perfect-c9.homes
        user: ubuntu
        key: ${{secrets.DEPLOY}}

          # pm2 restart "Express Server"
          # pm2 restart "Python Server"
          # pm2 start index.js --name "Express Server"
          # pm2 start server.py --name "Python Server"