name: deployment
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

env:
  POSTGRES_DB: perfectc9
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_DB: perfectc9
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          git pull
          yarn install 
          yarn add knex pg @types/pg
          yarn jest
  deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
    - name: ssh to pull latest version
      uses: fifsky/ssh-action@master
      with:
        command: |
          cat ~/.ssh/id_rsa
          cd perfect-c9/
          git pull
          npm install
          forever restart 0
        host: perfect-c9.homes
        user: ubuntu
        key: ${{secrets.DEPLOY}}